name: Dennis Jenders
favicon: null
layout_spectrum: 0.6619143569841981
typography_spectrum: 0.1060765900183469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.28915639594197273
  lightness: 0.7415862353518605
  saturation: 0.9198587986174971
  rhythmicContrast: 0.5450722072273493
purpose: []
